version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      # - ./volumes/elasticsearch/storage:/usr/share/elasticsearch/data:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - elk

  db:
    image: postgres:${DB_VERSION}-alpine
    environment:
        POSTGRES_USER: "$DB_USER"
        POSTGRES_PASSWORD: "$DB_PASSWORD"
        POSTGRES_DB: "$DB_NAME"
    volumes:
        - db:/var/lib/postgresql/data:z
    ports:
        - "127.0.0.1:5432:5432"

networks:

  elk:
    driver: bridge


volumes:
  db:
